apiVersion: v1
kind: ConfigMap
metadata:
  name: community-config
data:
  PORT: "80"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
      - name: community
        image: elive7/community:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: community-config
        - secretRef: 
            name: community-secret
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: community
  labels:
    app: community
spec:
  type: ClusterIP 
  selector:
    app: community
  ports:
    - port: 80
      targetPort: 80
