apiVersion: v1
kind: ConfigMap
metadata:
  name: community-config
data:
  PORT: "80"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
      - name: community
        image: elive7/community
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: community-config
        - secretRef: 
            name: community-secret

---
apiVersion: v1
kind: Service
metadata:
  name: community
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: community